Fully Developed Application
El-Potato-Slayer/js-restaurant pull request #1
Opened 2021-03-18 21:10 UTC by El-Potato-Slayer

- Contains a home, menu, and contact page
- Each page is loaded without to refresh
- Each page and logic have been separated into their respective modules
- All modules are exported in index.js

2021-03-18 21:36 UTC, wathigo requested changes
## CHANGES REQUIRED :o:  
Great job on this project.
Let's make a couple of changes as shown in the comments :point_down: 

**After making the changes, make another request for review.**

**Happy Coding :computer_mouse: :technologist: :computer: 
Simon Wathigo**

2021-03-18 21:36 UTC, wathigo commented on .vscode/settings.json
> +}
**REQUIRED**
* Files not related to the project should not be committed and added to .gitignore (e.g. .DS_Store) ([screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png))

2021-03-18 21:36 UTC, wathigo commented on package.json
> +  },
**REQUIRED**
Necessary run common commands like build, development should be in package.json inside `scripts'. Here is a basic example ([screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/scripts_requirement.png))

2021-03-19 03:38 UTC, arslanbisharat approved these changes
# Approved :clap:

Hello Developer, :wave:

Thank You for submitting this Pull Request. I am thrilled to announce that your project has met all the minimum requirements and now it is approved. :clap:

I am wishing you very good luck with the next project. :smile:

Once again, Congratulations!:joy:

**Best,
Arslan Bisharat(PT-TSE)
Slack: @arslanbisharat**

2021-05-10 02:44 UTC, merged